# Program4: Build an Artificial Neural Network by implementing the Backpropagation algorithm and test the same using appropriate data sets

In [1]:
import numpy as np
X=np.array(([2,9],[1,5],[3,6]), dtype=float)#Features(Hrs Slept, Hrs Studied)
y= np.array(([92], [86],[89]), dtype=float)#Labels(Marks obtained)
X =X/np.amax(X,axis=0) #Normalize
y=y/100

In [2]:
def sigmoid (x):
    return 1/(1 + np.exp(-x))
def sigmoid_grad(x):
    return x* (1-x)
#variable initialization
epoch=1000	#Setting training iterations
eta=0.2	#Setting leaning rate(eta)
input_neurons = 2 #number of features in data set
hidden_neurons =3 #number of hidden layers neurons
output_neurons =1 #number of neurons at output layer

In [3]:
#Weight and bias - Random initialization 
wh=np.random.uniform(size=(input_neurons,hidden_neurons)) 
bh=np.random.uniform(size=(1,hidden_neurons)) 
wout=np.random.uniform(size=(hidden_neurons,output_neurons)) 
bout=np.random.uniform(size=(1,output_neurons))

In [4]:
print(wh)
print(bh)

[[0.17343245 0.45600872 0.83551191]
 [0.67209947 0.01827431 0.84517983]]
[[0.63760851 0.73623432 0.54953059]]


In [5]:
print(wout)
print(bout)

[[0.27188798]
 [0.74494668]
 [0.46625695]]
[[0.46637817]]


In [4]:
for i in range(epoch):
#forward propogation
    h_ip=np.dot(X,wh)+bh
    h_act=sigmoid(h_ip)
    o_ip=np.dot(h_act,wout)
    output =sigmoid(o_ip)
    #Back propogation
    #Error at Outuput layer
    Eo = y-output
    outgrad=sigmoid_grad(output)
    d_output=Eo*outgrad
    #Error at Hidden layer
    Eh=d_output.dot(wout.T)
    hiddengrad=sigmoid_grad(h_act)
    d_hidden=Eh*hiddengrad
    wout += h_act.T.dot(d_output)*eta
    wh += X.T.dot(d_hidden)*eta
print("Normalized Input: \n"+ str(X))
print("Actual Output: \n"+ str(y))
print("Predicted Output : \n", output)

Normalized Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output : 
 [[0.8969548 ]
 [0.87694914]
 [0.89512028]]
